model:
  embedding_dim: 24
  hidden_dim: 352
  num_layers: 3
  activation: relu
  dropout: 0.40093608876750964
  batchnorm: false
  use_weight_norm: false
  residual: false
  final_activation: null
  task: regression
  context_mode: onehot
  target_names:
  - init
training:
  optimizer: adam
  weight_decay: 0.003970458050602785
  betas:
  - 0.9
  - 0.999
  eps: 1.0e-08
  batch_size: 256
  learning_rate: 0.0005071498892152174
  num_epochs: 340
  early_stopping_patience: 44
  early_stop_min_delta: 0.0015841806108443564
  lr_scheduler: plateau
  lr_decay_factor: 0.5756890716132887
  lr_decay_patience: 21
  plateau_threshold: 0.0001
  plateau_threshold_mode: rel
  lr_cooldown: 0
  min_lr: 0.0
  save_states: false
  log_training: false
  save_results: true
  save_model: false
  loss_reduction: per_class_equal
  regression_group_metric: rmse
  seed: 1234
interpretability:
  compute_shap: false
  shap_num_background: 128
  shap_num_samples: 256
  shap_kernel_nsamples: 200
  save_influence: false
  influence_step_fraction: 0.005
  sweep_range:
  - -3.0
  - 3.0
seed: 1234
